djangoapp/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = 'djangoapp'
urlpatterns = [
    # route is a string contains a URL pattern
    # view refers to the view function
    # name the URL
    path(route='', view=views.get_dealerships, name='index'),

    # path for about view
    path(route='about/', view=views.about, name='about'),
    # path for contact us view
    path(route='contact/', view=views.contact, name='contact'),
    # path for registration
    path(route='registration/', view=views.registration_Request, name='registration'),
    # path for login
    path(route='login/', view=views.login_Request, name='login'),
    # path for logout
    path(route='logout/', view=views.logout_Request, name='logout'), 
    #Path for get all dealerships to index
    path(route='', view=views.get_dealerships, name='index'),
    # path for dealer reviews view
    path('dealer/<int:id>/', views.get_dealer_details, name='dealer_details'),
    # path for add a review view
    path('dealer/<int:id>/review', views.add_review, name='add_review'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)\
 + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

djangobackend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('djangoapp/', include('djangoapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangoapp/models.py
from django.db import models
from django.utils.timezone import now
from django.core import serializers 
import uuid
import json

# Create your models here.

# <HINT> Create a Car Make model `class CarMake(models.Model)`:
# - Name
# - Description
# - Any other fields you would like to include in car make model
# - __str__ method to print a car make object

class CarMake(models.Model):
    name = models.CharField(null=False, max_length=100, default='Make')
    description = models.CharField(max_length=500)

    def __str__(self):
        return "Name: " + self.name


    


# <HINT> Create a Car Model model `class CarModel(models.Model):`:
# - Many-To-One relationship to Car Make model (One Car Make has many Car Models, using ForeignKey field)
# - Name
# - Dealer id, used to refer a dealer created in cloudant database
# - Type (CharField with a choices argument to provide limited choices such as Sedan, SUV, WAGON, etc.)
# - Year (DateField)
# - Any other fields you would like to include in car model
# - __str__ method to print a car make object
class CarModel(models.Model):
    id = models.IntegerField(default=1,primary_key=True)
    name = models.CharField(null=False, max_length=100, default='Car')
   
    SEDAN = 'Sedan'
    SUV = 'SUV'
    WAGON = 'Wagon'
    MINIVAN = 'Minivan'
    CAR_TYPES = [
        (SEDAN, 'Sedan'),
        (SUV, 'SUV'),
        (WAGON, 'Wagon'),
        (MINIVAN, 'Minivan')
    ]

    type = models.CharField(
        null=False,
        max_length=50,
        choices=CAR_TYPES,
        default=SEDAN
    )
    make = models.ForeignKey(CarMake, on_delete=models.CASCADE)
    year = models.DateField(default=now)

    def __str__(self):
        return "Name: " + self.name
    
# <HINT> Create a plain Python class `CarDealer` to hold dealer data
class CarDealer:

    def __init__(self, address, city, full_name, id, lat, long, short_name, st, zip):
        # Dealer address
        self.address = address
        # Dealer city
        self.city = city
        # Dealer Full Name
        self.full_name = full_name
        # Dealer id
        self.id = id
        # Location lat
        self.lat = lat
        # Location long
        self.long = long
        # Dealer short name
        self.short_name = short_name
        # Dealer state
        self.st = st
        # Dealer zip
        self.zip = zip

    def __str__(self):
        return "Dealer name: " + self.full_name

# <HINT> Create a plain Python class `DealerReview` to hold review data

class DealerReview:

    def __init__(self, dealership, name, purchase, review):
        # Required attributes
        self.dealership = dealership
        self.name = name
        self.purchase = purchase
        self.review = review
        # Optional attributes
        self.purchase_date = ""
        self.purchase_make = ""
        self.purchase_model = ""
        self.purchase_year = ""
        self.sentiment = ""
        self.id = ""

    def __str__(self):
        return "Review: " + self.review

    def to_json(self):
        return json.dumps(self, default=lambda o: o.__dict__,
                            sort_keys=True, indent=4)

class ReviewPost:

    def __init__(self, dealership, name, purchase, review):
        self.dealership = dealership
        self.name = name
        self.purchase = purchase
        self.review = review
        self.purchase_date = ""
        self.car_make = ""
        self.car_model = ""
        self.car_year = ""

    def to_json(self):
        return json.dumps(self, default=lambda o: o.__dict__,
                            sort_keys=True, indent=4)

djangoapp/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404, render, redirect
# from .models import related models
from .models import CarDealer, CarModel, CarMake, DealerReview, ReviewPost
# from .restapis import related methods
from .restapis import  get_dealer_reviews_from_cf, get_dealers_from_cf, get_dealer_by_id_from_cf, post_request
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from datetime import datetime
import logging
import json


# Get an instance of a logger
logger = logging.getLogger(__name__)


# Create your views here.

def djangoTemplate(request):
    context = {}
    if request.method =='GET':
        return render(request, 'djangoapp/index.html', context)
    
# Create an `about` view to render a static about page
# def about(request):
# ...
def about(request):
    context = {}
    if request.method == "GET":
        return render(request, 'djangoapp/about.html',context)


# Create a `contact` view to return a static contact page
#def contact(request):
def contact(request):
    context = {}
    if request.method == "GET":
        return render(request, 'djangoapp/contact.html', context)

# Create a `login_request` view to handle sign in request
# def login_request(request):
# ...
def login_Request(request):
    context = {}
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['psw']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('djangoapp:index')
        else:
            context['message'] = "Invalid username or password."
            return render(request, 'djangoapp/registration.html', context)
    else:
        return render(request, 'djangoapp/registration.html', context)

# Create a `logout_request` view to handle sign out request
# def logout_request(request):
# ...
def logout_Request(request):
    print("Logging out `{}`".format(request.user.username))
    logout(request)
    return redirect('djangoapp:index')


# Create a `registration_request` view to handle sign up request
# def registration_request(request):
# ...
def registration_Request(request):
    context = {}
    if request.method == 'GET':
        return render(request, 'djangoapp/registration.html', context)
    elif request.method == 'POST':
        # Check if user exists
        username = request.POST['username']
        password = request.POST['psw']
        first_name = request.POST['firstname']
        last_name = request.POST['lastname']
        user_exist = False
        try:
            User.objects.get(username=username)
            user_exist = True
        except:
            logger.error("New user")
        if not user_exist:
            user = User.objects.create_user(username=username, first_name=first_name, last_name=last_name,
                                            password=password)
            login(request, user)
            return redirect("djangoapp:index")
        else:
            context['message'] = "User already exists."
            return HttpResponse("djangoapp:index")

# Update the `get_dealerships` view to render the index page with a list of dealerships
def get_dealerships(request):
    print ("Get dealership Method Reached")
    context = {}
    if request.method == "GET":
        url = "https://d53467c6.us-south.apigw.appdomain.cloud/api/dealership"
        dealerships = get_dealers_from_cf(url)
        context["dealership_list"] = dealerships
        # print (context)
        return render(request,'djangoapp/index.html',context)
    else:
        print("check views.py line 110")

        


# Create a `get_dealer_details` view to render the reviews of a dealer
# def get_dealer_details(request, dealer_id):
# ...
def get_dealer_details(request, id):
    if request.method == "GET":
        context = {}
        dealer_url = "https://d53467c6.us-south.apigw.appdomain.cloud/api/dealership"
        dealer = get_dealer_by_id_from_cf(dealer_url, id=id)
        print (dealer)
        context["dealer"] = dealer
    
        review_url = "https://d53467c6.us-south.apigw.appdomain.cloud/api/review"
        reviews = get_dealer_reviews_from_cf(review_url, id=id)
        print(reviews)
        context["reviews"] = reviews
        
        return render(request, 'djangoapp/dealer_details.html', context)


# Create a `add_review` view to submit a review
# def add_review(request, dealer_id):
# ...
def add_review(request, id):
    context = {}
    dealer_url = "https://d53467c6.us-south.apigw.appdomain.cloud/api/dealership"
    dealer = get_dealer_by_id_from_cf(dealer_url, id=id)
    context["dealer"] = dealer
    print("add review method reached")
    if request.method == 'GET':
        # Get cars for the dealer
        cars = CarModel.objects.all()
        print(cars)
        context["cars"] = cars
        return render(request, 'djangoapp/add_review.html', context)
    
    elif request.method == 'POST':
        if request.user.is_authenticated:
            username = request.user.username
            print(request.POST)
            payload = dict()
            car_id = request.POST["car"]
            car = CarModel.objects.get(pk=car_id)
            payload["time"] = datetime.utcnow().isoformat()
            payload["name"] = username
            payload["dealership"] = id
            payload["id"] = id
            payload["review"] = request.POST["content"]
            payload["purchase"] = False
            if "purchasecheck" in request.POST:
                if request.POST["purchasecheck"] == 'on':
                    payload["purchase"] = True
            payload["purchase_date"] = request.POST["purchasedate"]
            payload["car_make"] = car.make.name
            payload["car_model"] = car.name
            payload["car_year"] = int(car.year.strftime("%Y"))

            new_payload = {}
            new_payload["review"] = payload
            review_post_url = "https://d53467c6.us-south.apigw.appdomain.cloud/api/review"
            post_request(review_post_url, new_payload, id=id)
        return redirect("djangoapp:dealer_details", id=id)

djangoapp/templates/djangoapp/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Dealership Review</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link href="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.css" rel="stylesheet">
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/extensions/filter-control/bootstrap-table-filter-control.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="about.css" media="screen"/>
</head>

    <body>
    <!--Add a nav bar here -->
    <nav class="navbar navbar-light bg-light">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class"navbar-brand" hred="#" onclick="location.href='{%url 'djangoapp:index' %}'">Best Car Dealership</a>
                <a class="btn" href="{%url 'djangoapp:about' %}"> About Us</a>
                <a class="btn" href="{%url 'djangoapp:contact' %}"> Contact Us</a>
            </div>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                <li>
                    <a class="btn btn-link" href="#">{{ user.first_name}}({{ user.username}})</a>
                    <a class="btn btn-link" href="{% url 'djangoapp:logout' %}">Logout</a>
                </li>
                {% else %}
                <li>
                    <form class="form-inline" action="{% url 'djangoapp:login' %}" method="post">
                        {% csrf_token %}
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Username" name="username" >
                            <input type="password" class="form-control" placeholder="Password" name="psw" >
                            <button class="btn btn-primary" type="submit">Login</button>
                            <a class="btn btn-link" href="{% url 'djangoapp:registration' %}">Sign Up</a>
                        </div>
                    </form>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <!--Add a dealer table here -->

    </body>

<html>
        <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <style>
        h1 {
          font-size:60px;
          font-family: "Brush Script MT"
        }
        h2 {
          font-size:40px;
          font-family: "Brush Script MT"
        }
        body {
          font-family: Arial, Helvetica, sans-serif;
          margin: 0;
        }
        
        html {
          box-sizing: border-box;
        }
        
        *, *:before, *:after {
          box-sizing: inherit;
        }
        
        .column {
          float: center;
          width: 33.3%;
          margin-bottom: 16px;
          padding: 0 8px;
        }
        
        .card {
          box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
          margin: 8px;
        }
        
        .about-section {
          padding: 30px;
          text-align: center;
          background-color: #474e5d;
          color: white;
        }
        
        .container {
          padding: 0 16px;
        }
        
        .container::after, .row::after {
          content: "";
          clear: both;
          display: table;
        }
        
        .title {
          color: grey;
        }
        
        .button {
          border: none;
          outline: 0;
          display: inline-block;
          padding: 8px;
          color: white;
          background-color: #000;
          text-align: center;
          cursor: pointer;
          width: 100%;
        }
        
        .button:hover {
          background-color: #555;
        }
        
        @media screen and (max-width: 650px) {
          .column {
            width: 100%;
            display: block;
          }
        }
        </style>
        </head>
        <body>
    <div class="about-section">
        <h1>Who We Are</h1>
        <p>Welcome to Best Cars dealership, home to the best cars in North America. We sell domestic and imported cars at reasonable prices.</p>

      </div>
      
      <h2 style="text-align:center">Our Team</h2>
      <div class="row">
        <div class="column">
          <div class="card">
            <img src="https://media.istockphoto.com/photos/wherever-she-goes-productivity-follows-picture-id879685072?k=20&m=879685072&s=612x612&w=0&h=49lV0_5P_SXw4NGuM_LPRl5M5-6p_V3yWTJtAyf6Xpg=" alt="Jane" style="width:100%">
            <div class="container">
              <h2>Jane Doe</h2>
              <p class="title">CEO & Founder</oremp>
              <p>Founder of the BEST car dealership in Northern America. Jane hailed from a business background, here to bring to the best deals.</p>
              
              <p><button class="button" onclick="location.href='{%url 'djangoapp:contact' %}'">Contact</button></p>
            </div>
          </div>
        </div>
      
        <div class="column">
          <div class="card">
            <img src="https://media.istockphoto.com/photos/car-dealer-standing-and-posing-in-showroom-picture-id1163423519?b=1&k=20&m=1163423519&s=170667a&w=0&h=LCobHrDTEidOMTQGEvZdfOIWE4FORFRtBhhMXxDz9Mc=" alt="Mike" style="width:100%">
            <div class="container">
              <h2>Mike Ross</h2>
              <p class="title">Expert Consultant</p>
              <p>Mike is our Expert Consultant to help you find everything you need in a vehicle. Find your perfect car.</p>
              
              <p><button class="button" onclick="location.href='{%url 'djangoapp:contact' %}'">Contact</button></p>
            </div>
          </div>
        </div>
      
        <div class="column">
          <div class="card">
            <img src="https://media.istockphoto.com/photos/friendly-business-owner-of-his-garage-workshop-holding-a-tablet-while-picture-id1349412692?b=1&k=20&m=1349412692&s=170667a&w=0&h=QHpmk-NNr-kAfsUn3fnH524R3kwEFFhEIkN4H6ISwys=" alt="John" style="width:100%">
            <div class="container">
              <h2>John Doe</h2>
              <p class="title">Expert Technician</p>
              <p>John is our Expert Technician trained with years of experience, here to provide you the top notch service your car deserves.</p>
              
              <p><button class="button" onclick="location.href='{%url 'djangoapp:contact' %}'">Contact</button></p>
            </div>
          </div>
        </div>
      </div>
</html>

djangoapp/templates/djangoapp/add_review.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.0/css/bootstrap-datepicker.css" rel="stylesheet">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.0/js/bootstrap-datepicker.js"></script>

</head>
<body>
    <div class="container-fluid">
        <h3>Add a review about <b>{{dealer.full_name}}</b></h3>
        <form action="{% url 'djangoapp:add_review' dealer.id%}" method="post">
            <div class="form-group">
    
                  <div class="mb-3">
                      <label for="content"><b>Enter the review: </b></label>
                      <textarea class="form-control" id="content" name="content" rows="2" required></textarea>
                  </div>
    
                  <div class="form-check">
                      <input class="form-check-input" type="checkbox" name="purchasecheck" id="purchasecheck">
                      <label class="form-check-label" for="purchasecheck">
                          Has purchased the car from {{dealer.full_name}} ?
                      </label>
                      <label class="text-muted">(select purchased car information below if checked)</label>
                  </div>
    
                  <div class="mb-3">
                      <label for="car"><b>Select your car (model-type-year):</b></label>
                      <select name="car" id="car" class="form-select" required>
                          {% for car in cars %}
                          <option selected value={{car.id}}>{{car.name}}-{{car.type.name}}-{{ car.year|date:"Y" }}</option>
                          {% endfor %}
                      </select>
                  </div>
    
                  <div class="mb-3">
                      <label for="purchasedate"><b>Select Your Purchase Date: </b></label>
                      <input class="date-own form-control" style="width: 300px;" type="text" name="purchasedate" id="purchasedate">
                  </div>
    
            </div>
            {% csrf_token %}
            <div>
                <button class="btn btn-primary" type="submit">Submit</button>
            </div>
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-warning" role="alert">{{ message }}</div>
                {% endfor %}
            {% endif %}
        </form>
    </div>
    </body>
    
    <script type="text/javascript">
          $('.date-own').datepicker({
             format: 'mm/dd/yyyy'
           });
     </script>

djangoapp/templates/djangoapp/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Dealership Review</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link href="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.css" rel="stylesheet">
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/extensions/filter-control/bootstrap-table-filter-control.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>

    <body>
    <!--Add a nav bar here -->
    <nav class="navbar navbar-light bg-light">
      <div class="container-fluid">
          <div class="navbar-header">
              <a class"navbar-brand" hred="#" onclick="location.href='{%url 'djangoapp:index' %}'">Best Car Dealership</a>
              <a class="btn" href="{%url 'djangoapp:about' %}"> About Us</a>
              <a class="btn" href="{%url 'djangoapp:contact' %}"> Contact Us</a>
          </div>
          <ul class="nav navbar-nav navbar-right">
              {% if user.is_authenticated %}
              <li>
                  <a class="btn btn-link" href="#">{{ user.first_name}}({{ user.username}})</a>
                  <a class="btn btn-link" href="{% url 'djangoapp:logout' %}">Logout</a>
              </li>
              {% else %}
              <li>
                  <form class="form-inline" action="{% url 'djangoapp:login' %}" method="post">
                      {% csrf_token %}
                      <div class="input-group">
                          <input type="text" class="form-control" placeholder="Username" name="username" >
                          <input type="password" class="form-control" placeholder="Password" name="psw" >
                          <button class="btn btn-primary" type="submit">Login</button>
                          <a class="btn btn-link" href="{% url 'djangoapp:registration' %}">Sign Up</a>
                      </div>
                  </form>
              </li>
              {% endif %}
          </ul>
      </div>
  </nav>

    <!--Add a dealer table here -->

    </body>

</html>

<html>
        <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <style>
        h1 {
          font-family: "Brush Script MT";
          font-size: 60px;
        }
        h2 {
          font-family: "Brush Script MT";
          font-size: 40px;
        }
        body {
          font-family: Arial, Helvetica, sans-serif;
          margin: 0;
        }
        
        html {
          box-sizing: border-box;
        }
        
        *, *:before, *:after {
          box-sizing: inherit;
        }
        
        .column {
          float: left;
          width: 33.3%;
          margin-bottom: 16px;
          padding: 0 8px;
        }
        
        .card {
          box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
          margin: 8px;
        }g
        
        .about-section {
          padding: 50px;
          text-align: center;
          background-color: #474e5d;
          color: white;
        }
        
        .container {
          padding: 0 16px;
        }
        
        .container::after, .row::after {
          content: "";
          clear: both;
          display: table;
        }
        
        .title {
          color: grey;
        }
        
        .button {
          border: none;
          outline: 0;
          display: inline-block;
          padding: 8px;
          color: white;
          background-color: #000;
          text-align: center;
          cursor: pointer;
          width: 100%;
        }
        
        .button:hover {
          background-color: #555;
        }
        
        @media screen and (max-width: 650px) {
          .column {
            width: 100%;
            display: block;
          }
        }
        </style>
        </head>
        <body>
    <div class="about-section">
        <h1>Contact Us</h1>

      </div>
      
      <h2 style="text-align:center">Our Team</h2>
      <div class="row">
        <div class="column">
          <div class="card">
            <img src="https://media.istockphoto.com/photos/wherever-she-goes-productivity-follows-picture-id879685072?k=20&m=879685072&s=612x612&w=0&h=49lV0_5P_SXw4NGuM_LPRl5M5-6p_V3yWTJtAyf6Xpg=" alt="Jane" style="width:100%">
            <div class="container">
              <h2>Jane Doe</h2>
              <p class="title">CEO & Founder</oremp>
              <p>123-422-2313</p>
              <gp>jane@example.com</p>
              
            </div>
          </div>
        </div>
      
        <div class="column">
          <div class="card">
            <img src="https://media.istockphoto.com/photos/car-dealer-standing-and-posing-in-showroom-picture-id1163423519?b=1&k=20&m=1163423519&s=170667a&w=0&h=LCobHrDTEidOMTQGEvZdfOIWE4FORFRtBhhMXxDz9Mc=" alt="Mike" style="width:100%">
            <div class="container">
              <h2>Mike Ross</h2>
              <p class="title">Expert Consultant</p>
              <p>123-242-2323</p>
              <p>mike@example.com</p>
              
            </div>
          </div>
        </div>
      
        <div class="column">
          <div class="card">
            <img src="https://media.istockphoto.com/photos/friendly-business-owner-of-his-garage-workshop-holding-a-tablet-while-picture-id1349412692?b=1&k=20&m=1349412692&s=170667a&w=0&h=QHpmk-NNr-kAfsUn3fnH524R3kwEFFhEIkN4H6ISwys=" alt="John" style="width:100%">
            <div class="container">
              <h2>John Doe</h2>
              <p class="title">Expert Technician</p>
              <p>214-232-2323</p>
              <p>john@example.com</p>
            </div>
          </div>
        </div>
      </div>

      <h2 style="text-align:center">
      <p></p>
      <p>123 Street Ave.</p>
      <p>Santa Cruz, CA</p>
      <p>12345</p>
      </h2>
</html>

djangoapp/templates/djangoapp/dealer_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Dealership Review</title>
    {% load static %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>

    <body>

    <!--Add a nav bar here -->
    <nav class="navbar navbar-light bg-light">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class"navbar-brand" hred="#" onclick="location.href='{%url 'djangoapp:index' %}'">Best Car Dealership</a>
                <a class="btn" href="{%url 'djangoapp:about' %}"> About Us</a>
                <a class="btn" href="{%url 'djangoapp:contact' %}"> Contact Us</a>
            </div>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                <li>
                    <a class="btn btn-link" href="#">{{ user.first_name}}({{ user.username}})</a>
                    <a class="btn btn-link" href="{% url 'djangoapp:logout' %}">Logout</a>
                </li>
                {% else %}
                <li>
                    <form class="form-inline" action="{% url 'djangoapp:login' %}" method="post">
                        {% csrf_token %}
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Username" name="username" >
                            <input type="password" class="form-control" placeholder="Password" name="psw" >
                            <button class="btn btn-primary" type="submit">Login</button>
                            <a class="btn btn-link" href="{% url 'djangoapp:registration' %}">Sign Up</a>
                        </div>
                    </form>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <!-- Add reviews as cards -->
    <div class="container-fluid">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-warning" role="alert">{{ message }}</div>
            {% endfor %}
        {% endif %}
    
        <h3>Reviews for Dealer_id <b>{{dealer.id}}</b></h3>
    
        <div class="container">
            <div class="card-columns">
                {% for dealer_review in reviews %}
                <div class="col-auto mb-3">
                    <div class="card">
                        {% if dealer_review.sentiment == "positive" %}
                            <img class="card-img-left" src="{{MEDIA_URL}}/emoji/positive.png" width="36px" height="36px"
                                 alt="Sentiment">
                        {% elif dealer_review.sentiment == "negative" %}
                            <img class="card-img-left" src="{{MEDIA_URL}}/emoji/negative.png" width="36px" height="36px"
                                       alt="Sentiment">
                            {% else %}
                            <img class="card-img-left" src="{{MEDIA_URL}}/emoji/neutral.png" width="36px" height="36px"
                                       alt="Sentiment">
                        {% endif %}
                        <div class="card-body bg-light">
                                  {% if dealer_review.car_make%}
                                      <h5 class="card-title">{{dealer_review.car_make}}, {{dealer_review.car_model}} </h5>
                                      <h5 class="card-title">{{dealer_review.car_year}}</h5>
                                   {% endif %}
                                  <p class="card-text">{{dealer_review.review}}</p>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <a class="btn btn-link" href="{% url 'djangoapp:add_review' dealer.id%}">Add Review</a>
    </body>
    
    
    </html>